//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_System_Cleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool registryCleanerOptionsLog {
            get {
                return ((bool)(this["registryCleanerOptionsLog"]));
            }
            set {
                this["registryCleanerOptionsLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool registryCleanerOptionsShowLog {
            get {
                return ((bool)(this["registryCleanerOptionsShowLog"]));
            }
            set {
                this["registryCleanerOptionsShowLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool registryCleanerOptionsRemMedia {
            get {
                return ((bool)(this["registryCleanerOptionsRemMedia"]));
            }
            set {
                this["registryCleanerOptionsRemMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsUpdate {
            get {
                return ((bool)(this["optionsUpdate"]));
            }
            set {
                this["optionsUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsSysRestore {
            get {
                return ((bool)(this["optionsSysRestore"]));
            }
            set {
                this["optionsSysRestore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool registryCleanerOptionsDelBackup {
            get {
                return ((bool)(this["registryCleanerOptionsDelBackup"]));
            }
            set {
                this["registryCleanerOptionsDelBackup"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bugReportAddr {
            get {
                return ((string)(this["bugReportAddr"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool registryCleanerOptionsAutoRescan {
            get {
                return ((bool)(this["registryCleanerOptionsAutoRescan"]));
            }
            set {
                this["registryCleanerOptionsAutoRescan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool registryCleanerOptionsAutoRepair {
            get {
                return ((bool)(this["registryCleanerOptionsAutoRepair"]));
            }
            set {
                this["registryCleanerOptionsAutoRepair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool registryCleanerOptionsAutoExit {
            get {
                return ((bool)(this["registryCleanerOptionsAutoExit"]));
            }
            set {
                this["registryCleanerOptionsAutoExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool updateAuto {
            get {
                return ((bool)(this["updateAuto"]));
            }
            set {
                this["updateAuto"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://updates.little-apps.com/little-system-cleaner.xml")]
        public string updateURL {
            get {
                return ((string)(this["updateURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long lastScanDate {
            get {
                return ((long)(this["lastScanDate"]));
            }
            set {
                this["lastScanDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastScanErrors {
            get {
                return ((int)(this["lastScanErrors"]));
            }
            set {
                this["lastScanErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastScanErrorsFixed {
            get {
                return ((int)(this["lastScanErrorsFixed"]));
            }
            set {
                this["lastScanErrorsFixed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long lastScanElapsed {
            get {
                return ((long)(this["lastScanElapsed"]));
            }
            set {
                this["lastScanElapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalScans {
            get {
                return ((int)(this["totalScans"]));
            }
            set {
                this["totalScans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalErrorsFound {
            get {
                return ((int)(this["totalErrorsFound"]));
            }
            set {
                this["totalErrorsFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalErrorsFixed {
            get {
                return ((int)(this["totalErrorsFixed"]));
            }
            set {
                this["totalErrorsFixed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int totalRuns {
            get {
                return ((int)(this["totalRuns"]));
            }
            set {
                this["totalRuns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerSearchSystem {
            get {
                return ((bool)(this["diskCleanerSearchSystem"]));
            }
            set {
                this["diskCleanerSearchSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool diskCleanerSearchReadOnly {
            get {
                return ((bool)(this["diskCleanerSearchReadOnly"]));
            }
            set {
                this["diskCleanerSearchReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool diskCleanerSearchHidden {
            get {
                return ((bool)(this["diskCleanerSearchHidden"]));
            }
            set {
                this["diskCleanerSearchHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool diskCleanerSearchArchives {
            get {
                return ((bool)(this["diskCleanerSearchArchives"]));
            }
            set {
                this["diskCleanerSearchArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerSearchZeroByte {
            get {
                return ((bool)(this["diskCleanerSearchZeroByte"]));
            }
            set {
                this["diskCleanerSearchZeroByte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerRemoveMode {
            get {
                return ((int)(this["diskCleanerRemoveMode"]));
            }
            set {
                this["diskCleanerRemoveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string diskCleanerMoveFolder {
            get {
                return ((string)(this["diskCleanerMoveFolder"]));
            }
            set {
                this["diskCleanerMoveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool diskCleanerAutoRestorePoints {
            get {
                return ((bool)(this["diskCleanerAutoRestorePoints"]));
            }
            set {
                this["diskCleanerAutoRestorePoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerFilterMode {
            get {
                return ((int)(this["diskCleanerFilterMode"]));
            }
            set {
                this["diskCleanerFilterMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.tmp; *.temp; *.gid; *.chk; *.~*;")]
        public string diskCleanerSearchFilters {
            get {
                return ((string)(this["diskCleanerSearchFilters"]));
            }
            set {
                this["diskCleanerSearchFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool diskCleanerIgnoreWriteProtected {
            get {
                return ((bool)(this["diskCleanerIgnoreWriteProtected"]));
            }
            set {
                this["diskCleanerIgnoreWriteProtected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerFindFilesMode {
            get {
                return ((int)(this["diskCleanerFindFilesMode"]));
            }
            set {
                this["diskCleanerFindFilesMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerFindFilesAfter {
            get {
                return ((bool)(this["diskCleanerFindFilesAfter"]));
            }
            set {
                this["diskCleanerFindFilesAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerFindFilesBefore {
            get {
                return ((bool)(this["diskCleanerFindFilesBefore"]));
            }
            set {
                this["diskCleanerFindFilesBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/14/2010 21:39:00")]
        public global::System.DateTime diskCleanerDateTimeAfter {
            get {
                return ((global::System.DateTime)(this["diskCleanerDateTimeAfter"]));
            }
            set {
                this["diskCleanerDateTimeAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06/14/2010 21:39:00")]
        public global::System.DateTime diskCleanerDateTimeBefore {
            get {
                return ((global::System.DateTime)(this["diskCleanerDateTimeBefore"]));
            }
            set {
                this["diskCleanerDateTimeBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>?:\program files\common files</string>
  <string>?:\program files\uninstall information</string>
  <string>?:\win*\security</string>
  <string>*\sendto</string>
  <string>*\i386</string>
  <string>*\resources\themes</string>
  <string>*\microsoft\office\data</string>
  <string>*\microsoft\money\*\webcache</string>
  <string>*\chaos32</string>
  <string>*\paprport\data</string>
  <string>*\symantec shared\virusdefs</string>
  <string>?:\system volume information</string>
  <string>?:\_restore</string>
  <string>?:\recycle?</string>
  <string>*\temp\incredimail</string>
  <string>*\norton antivirus\quarantine</string>
  <string>*\system32\usmt</string>
  <string>*\system32\catroot2</string>
  <string>*\application data\microsoft</string>
  <string>?:\windows</string>
  <string>?:\winnt</string>
  <string>?:\win*\pif</string>
  <string>?:\win*\resources</string>
  <string>\win*\system32\oldole</string>
  <string>?:\win*\Sysbackup</string>
  <string>?:\win*\system32\olebackup</string>
  <string>?:\win*\system32\usmt</string>
  <string>?:\$recycle.bin</string>
  <string>*\Application Data\Aim</string>
  <string>*\symantec shared\virusdefs</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection diskCleanerExcludedDirs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["diskCleanerExcludedDirs"]));
            }
            set {
                this["diskCleanerExcludedDirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>config.*</string>
  <string>autoexec.*</string>
  <string>data.bak</string>
  <string>_Default.pif</string>
  <string>Calendar.tmp</string>
  <string>Data.sav</string>
  <string>Default.pif</string>
  <string>Donotdel.tmp</string>
  <string>DonotDelete.tmp</string>
  <string>Drelres.pif</string>
  <string>FTP.log</string>
  <string>Http.log</string>
  <string>Index.dat</string>
  <string>Install.log</string>
  <string>MM2048.DAT</string>
  <string>MM256.DAT</string>
  <string>Modem.log</string>
  <string>Script.bak</string>
  <string>System.old</string>
  <string>Uninstall.log</string>
  <string>User.old</string>
  <string>WebPoolFileFile</string>
  <string>Win.bak</string>
  <string>Win.old</string>
  <string>Wnccdctl.log</string>
  <string>wz.pif</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection diskCleanerExcludedFileTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["diskCleanerExcludedFileTypes"]));
            }
            set {
                this["diskCleanerExcludedFileTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerFindNotAccessed {
            get {
                return ((bool)(this["diskCleanerFindNotAccessed"]));
            }
            set {
                this["diskCleanerFindNotAccessed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerFindNotAccessedValue {
            get {
                return ((int)(this["diskCleanerFindNotAccessedValue"]));
            }
            set {
                this["diskCleanerFindNotAccessedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerCheckFileSize {
            get {
                return ((bool)(this["diskCleanerCheckFileSize"]));
            }
            set {
                this["diskCleanerCheckFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerCheckFileSizeLeast {
            get {
                return ((int)(this["diskCleanerCheckFileSizeLeast"]));
            }
            set {
                this["diskCleanerCheckFileSizeLeast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diskCleanerCheckFileSizeMost {
            get {
                return ((int)(this["diskCleanerCheckFileSizeMost"]));
            }
            set {
                this["diskCleanerCheckFileSizeMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool diskCleanerAutoClean {
            get {
                return ((bool)(this["diskCleanerAutoClean"]));
            }
            set {
                this["diskCleanerAutoClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList diskCleanerDiskDrives {
            get {
                return ((global::System.Collections.ArrayList)(this["diskCleanerDiskDrives"]));
            }
            set {
                this["diskCleanerDiskDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection diskCleanerIncludedFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["diskCleanerIncludedFolders"]));
            }
            set {
                this["diskCleanerIncludedFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int optionsUpdateDelay {
            get {
                return ((int)(this["optionsUpdateDelay"]));
            }
            set {
                this["optionsUpdateDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsUsageStats {
            get {
                return ((bool)(this["optionsUsageStats"]));
            }
            set {
                this["optionsUsageStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool privacyCleanerDeletePerm {
            get {
                return ((bool)(this["privacyCleanerDeletePerm"]));
            }
            set {
                this["privacyCleanerDeletePerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool privacyCleanerDeleteRecBin {
            get {
                return ((bool)(this["privacyCleanerDeleteRecBin"]));
            }
            set {
                this["privacyCleanerDeleteRecBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool privacyCleanerIncSysFile {
            get {
                return ((bool)(this["privacyCleanerIncSysFile"]));
            }
            set {
                this["privacyCleanerIncSysFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool privacyCleanerIncReadOnlyFile {
            get {
                return ((bool)(this["privacyCleanerIncReadOnlyFile"]));
            }
            set {
                this["privacyCleanerIncReadOnlyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool privacyCleanerIncHiddenFile {
            get {
                return ((bool)(this["privacyCleanerIncHiddenFile"]));
            }
            set {
                this["privacyCleanerIncHiddenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool privacyCleanerInc0ByteFile {
            get {
                return ((bool)(this["privacyCleanerInc0ByteFile"]));
            }
            set {
                this["privacyCleanerInc0ByteFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool privacyCleanerAutoSkipScanner {
            get {
                return ((bool)(this["privacyCleanerAutoSkipScanner"]));
            }
            set {
                this["privacyCleanerAutoSkipScanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool privacyCleanerLog {
            get {
                return ((bool)(this["privacyCleanerLog"]));
            }
            set {
                this["privacyCleanerLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool privacyCleanerDisplayLog {
            get {
                return ((bool)(this["privacyCleanerDisplayLog"]));
            }
            set {
                this["privacyCleanerDisplayLog"] = value;
            }
        }
    }
}
